# Travis CI settings

language: python

python:
  - '3.4'

env:
  matrix:
    - DB=sqlite DJANGO_VERSION=1.9.2

install:
  - pip install -U pip
  - pip install -r requirements.txt

before_script:

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - python3 mysite/manage.py migrate
  - sleep 3
  - export EMAIL_HOST_USER="test@example.com"
  - export SECRET_KEY="78m5@7^h(lne^@08$0@dn5i%96v^*u@v+1zp9_5t!iagf5319v"
  - export EMAIL_HOST_PASSWORD="password"

script:
  - python3 mysite/manage.py test blog
  - python3 mysite/manage.py test mysite/functional_tests
  - python3 -m pylint mysite/blog
